In [1]:
import pandas as pd
pd.options.mode.chained_assignment = None

Wczytuję tabelę, sprawdzam, jakie dane zawierają oraz sprawdzam typy danych w kolumnach.

In [2]:
df1 = pd.read_csv('NewCustomers.csv')
df2 = pd.read_csv('BranchCustomers.csv')

In [3]:
df1

,ID,Name,Address,city,state,zip,ContactPref,Contact,DOB
0,C1,jill franks,111 Lake Dr,Pgh,Pa,15212.0,email,jf773@hotmail.com,8/15/1995
1,C2,sal yates,57 College Way,Morgantown,WV,26501.0,phone,724-234-6542,6/4/1943
2,C3,will ratliff,544 Fifth Ave,Pgh,Pa,15219.0,email,ratty@mail.com,10/15/1951
3,C4,fran vicks,10332 West Street,McCandless,PA,15234.0,phone,904-123-8337,3/8/1968
4,C5,kline's,500 West South Street,Pgh,PA,15219.0,email,klines2@klines.com,7/13/1995
5,C6,olive pless,"6767 W 54th Street, Apt B",NaN,NaN,NaN,email,opless@newpc.com,12/15/1964

In [4]:
df2

,cusnum,cusfname,cuslname,cusmiddle,cusemail,cusphone,cusaddress1,cusaddress2,cuscity,cusstate,cuszip,cusfirstorder,cusrecentorder,cuszone,cusannualsales,currentbalance
0,A01,Jim,Semp,A,jsemp@mail.com,123-654-2344,123 Main Street,Suite 23,Pittsburgh,PA,15217-2233,3/1/1995,5/1/2001,North,10000,200
1,A03,Laura,Vail,NaN,laura.vail@hotmail.com,756-345-6789,23 Oak Lane,NaN,Morgantown,WV,26501,12/4/2002,6/1/2003,North,5000,314
2,A05,Al's Bakery,NaN,NaN,al@alsbakery.com,213-543-2342,846 Fifth Ave,NaN,Pittsburgh,PA,15219-1222,1/15/1999,8/12/2001,Central,15000,0
3,A07,Janet,Wendell,R,jwen@yahoo.com,434-786-3453,23212 Fern Circle,Apt 100,Washington,DC,20001,5/9/2010,11/24/2011,West,12500,798
4,A09,Alicia,Albert,NaN,aalbert@gmail.com,234-678-9234,432 Forbes Ave,NaN,Pittsburgh,PA,15229,3/2/2006,6/3/2009,South,500,125
5,A11,Henry,Kobb,NaN,hank@kobbfam.net,234-098-7464,10 Dairy Way,2nd Floor,Pittsburgh,PA,15229-8821,8/21/2004,3/5/2006,East,1300,57
6,A13,Corner Market,NaN,NaN,manager@cornermarket.com,222-837-6455,1500 Bruster Way,NaN,Ross,PA,15237,6/14/2007,6/2/2012,Central,13750,341
7,A15,Paul,Tolby,E,pt23@school.edu,995-234-5656,230 Route 12,NaN,Ross,PA,15237,4/3/1999,7/13/2001,East,2500,75
8,A17,Olive,Pless,NaN,opless@pctech.com,234-765-2233,15 Horse Alley,NaN,Oakland,PA,15213-8260,10/12/2000,9/16/2002,West,7500,213
9,A19,Remmy,Walker,L,walk.r@aol.com,969-234-8367,100 Silver Hwy,NaN,Oakland,PA,15213,6/1/2012,8/1/2012,South,20000,0

In [5]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ID           6 non-null      object
 1   Name         6 non-null      object
 2   Address      6 non-null      object
 3   city         5 non-null      object
 4   state        5 non-null      object
 5   zip          5 non-null      float64
 6   ContactPref  6 non-null      object
 7   Contact      6 non-null      object
 8   DOB          6 non-null      object
dtypes: float64(1), object(8)
memory usage: 560.0+ bytes

In [6]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   cusnum          10 non-null     object
 1   cusfname        10 non-null     object
 2   cuslname        8 non-null      object
 3   cusmiddle       4 non-null      object
 4   cusemail        10 non-null     object
 5   cusphone        10 non-null     object
 6   cusaddress1     10 non-null     object
 7   cusaddress2     3 non-null      object
 8   cuscity         10 non-null     object
 9   cusstate        10 non-null     object
 10  cuszip          10 non-null     object
 11  cusfirstorder   10 non-null     object
 12  cusrecentorder  10 non-null     object
 13  cuszone         10 non-null     object
 14  cusannualsales  10 non-null     int64
 15  currentbalance  10 non-null     int64
dtypes: int64(2), object(14)
memory usage: 1.4+ KB

Usuwam białe znaki w potrzebnych później kolumnach o typie string.

In [7]:
df1['Name'] = df1['Name'].str.strip()
df1['Address'] = df1['Address'].str.strip()
df1['city'] = df1['city'].str.strip()
df1['state'] = df1['state'].str.strip()
df1['ContactPref'] = df1['ContactPref'].str.strip()
df1['Contact'] = df1['Contact'].str.strip()

In [8]:
df2['cusnum'] = df2['cusnum'].str.strip()
df2['cusfname'] = df2['cusfname'].str.strip()
df2['cuslname'] = df2['cuslname'].str.strip()
df2['cusmiddle'] = df2['cusmiddle'].str.strip()
df2['cusemail'] = df2['cusemail'].str.strip()
df2['cusphone'] = df2['cusphone'].str.strip()
df2['cusaddress1'] = df2['cusaddress1'].str.strip()
df2['cusaddress2'] = df2['cusaddress2'].str.strip()
df2['cuscity'] = df2['cuscity'].str.strip()
df2['cusstate'] = df2['cusstate'].str.strip()
df2['cuszip'] = df2['cuszip'].str.strip()

Ujedolicam tabele.

In [9]:
df1 = df1.assign(email = df1[df1["ContactPref"] == 'email'].Contact)
df1 = df1.assign(phone = df1[df1["ContactPref"] == 'phone'].Contact)

In [10]:
df1

,ID,Name,Address,city,state,zip,ContactPref,Contact,DOB,email,phone
0,C1,jill franks,111 Lake Dr,Pgh,Pa,15212.0,email,jf773@hotmail.com,8/15/1995,jf773@hotmail.com,NaN
1,C2,sal yates,57 College Way,Morgantown,WV,26501.0,phone,724-234-6542,6/4/1943,NaN,724-234-6542
2,C3,will ratliff,544 Fifth Ave,Pgh,Pa,15219.0,email,ratty@mail.com,10/15/1951,ratty@mail.com,NaN
3,C4,fran vicks,10332 West Street,McCandless,PA,15234.0,phone,904-123-8337,3/8/1968,NaN,904-123-8337
4,C5,kline's,500 West South Street,Pgh,PA,15219.0,email,klines2@klines.com,7/13/1995,klines2@klines.com,NaN
5,C6,olive pless,"6767 W 54th Street, Apt B",NaN,NaN,NaN,email,opless@newpc.com,12/15/1964,opless@newpc.com,NaN

In [11]:
df1[['name', 'last name']] = df1['Name'].str.split(' ', expand=True)

In [12]:
df1['name'] = df1['name'].str.capitalize()
df1['last name'] = df1['last name'].str.capitalize()

In [13]:
df1

,ID,Name,Address,city,state,zip,ContactPref,Contact,DOB,email,phone,name,last name
0,C1,jill franks,111 Lake Dr,Pgh,Pa,15212.0,email,jf773@hotmail.com,8/15/1995,jf773@hotmail.com,NaN,Jill,Franks
1,C2,sal yates,57 College Way,Morgantown,WV,26501.0,phone,724-234-6542,6/4/1943,NaN,724-234-6542,Sal,Yates
2,C3,will ratliff,544 Fifth Ave,Pgh,Pa,15219.0,email,ratty@mail.com,10/15/1951,ratty@mail.com,NaN,Will,Ratliff
3,C4,fran vicks,10332 West Street,McCandless,PA,15234.0,phone,904-123-8337,3/8/1968,NaN,904-123-8337,Fran,Vicks
4,C5,kline's,500 West South Street,Pgh,PA,15219.0,email,klines2@klines.com,7/13/1995,klines2@klines.com,NaN,Kline's,None
5,C6,olive pless,"6767 W 54th Street, Apt B",NaN,NaN,NaN,email,opless@newpc.com,12/15/1964,opless@newpc.com,NaN,Olive,Pless

In [14]:
df2["cusmiddle"] = df2["cusmiddle"].fillna("")
df2["cusaddress2"] = df2["cusaddress2"].fillna("")

In [15]:
df2

,cusnum,cusfname,cuslname,cusmiddle,cusemail,cusphone,cusaddress1,cusaddress2,cuscity,cusstate,cuszip,cusfirstorder,cusrecentorder,cuszone,cusannualsales,currentbalance
0,A01,Jim,Semp,A,jsemp@mail.com,123-654-2344,123 Main Street,Suite 23,Pittsburgh,PA,15217-2233,3/1/1995,5/1/2001,North,10000,200
1,A03,Laura,Vail,,laura.vail@hotmail.com,756-345-6789,23 Oak Lane,,Morgantown,WV,26501,12/4/2002,6/1/2003,North,5000,314
2,A05,Al's Bakery,NaN,,al@alsbakery.com,213-543-2342,846 Fifth Ave,,Pittsburgh,PA,15219-1222,1/15/1999,8/12/2001,Central,15000,0
3,A07,Janet,Wendell,R,jwen@yahoo.com,434-786-3453,23212 Fern Circle,Apt 100,Washington,DC,20001,5/9/2010,11/24/2011,West,12500,798
4,A09,Alicia,Albert,,aalbert@gmail.com,234-678-9234,432 Forbes Ave,,Pittsburgh,PA,15229,3/2/2006,6/3/2009,South,500,125
5,A11,Henry,Kobb,,hank@kobbfam.net,234-098-7464,10 Dairy Way,2nd Floor,Pittsburgh,PA,15229-8821,8/21/2004,3/5/2006,East,1300,57
6,A13,Corner Market,NaN,,manager@cornermarket.com,222-837-6455,1500 Bruster Way,,Ross,PA,15237,6/14/2007,6/2/2012,Central,13750,341
7,A15,Paul,Tolby,E,pt23@school.edu,995-234-5656,230 Route 12,,Ross,PA,15237,4/3/1999,7/13/2001,East,2500,75
8,A17,Olive,Pless,,opless@pctech.com,234-765-2233,15 Horse Alley,,Oakland,PA,15213-8260,10/12/2000,9/16/2002,West,7500,213
9,A19,Remmy,Walker,L,walk.r@aol.com,969-234-8367,100 Silver Hwy,,Oakland,PA,15213,6/1/2012,8/1/2012,South,20000,0

In [16]:
df2["name"] = df2["cusfname"] + ' ' + df2["cusmiddle"]
df2["address"] = df2["cusaddress1"] + ', ' + df2["cusaddress2"]

In [17]:
df2

,cusnum,cusfname,cuslname,cusmiddle,cusemail,cusphone,cusaddress1,cusaddress2,cuscity,cusstate,cuszip,cusfirstorder,cusrecentorder,cuszone,cusannualsales,currentbalance,name,address
0,A01,Jim,Semp,A,jsemp@mail.com,123-654-2344,123 Main Street,Suite 23,Pittsburgh,PA,15217-2233,3/1/1995,5/1/2001,North,10000,200,Jim A,"123 Main Street, Suite 23"
1,A03,Laura,Vail,,laura.vail@hotmail.com,756-345-6789,23 Oak Lane,,Morgantown,WV,26501,12/4/2002,6/1/2003,North,5000,314,Laura,"23 Oak Lane,"
2,A05,Al's Bakery,NaN,,al@alsbakery.com,213-543-2342,846 Fifth Ave,,Pittsburgh,PA,15219-1222,1/15/1999,8/12/2001,Central,15000,0,Al's Bakery,"846 Fifth Ave,"
3,A07,Janet,Wendell,R,jwen@yahoo.com,434-786-3453,23212 Fern Circle,Apt 100,Washington,DC,20001,5/9/2010,11/24/2011,West,12500,798,Janet R,"23212 Fern Circle, Apt 100"
4,A09,Alicia,Albert,,aalbert@gmail.com,234-678-9234,432 Forbes Ave,,Pittsburgh,PA,15229,3/2/2006,6/3/2009,South,500,125,Alicia,"432 Forbes Ave,"
5,A11,Henry,Kobb,,hank@kobbfam.net,234-098-7464,10 Dairy Way,2nd Floor,Pittsburgh,PA,15229-8821,8/21/2004,3/5/2006,East,1300,57,Henry,"10 Dairy Way, 2nd Floor"
6,A13,Corner Market,NaN,,manager@cornermarket.com,222-837-6455,1500 Bruster Way,,Ross,PA,15237,6/14/2007,6/2/2012,Central,13750,341,Corner Market,"1500 Bruster Way,"
7,A15,Paul,Tolby,E,pt23@school.edu,995-234-5656,230 Route 12,,Ross,PA,15237,4/3/1999,7/13/2001,East,2500,75,Paul E,"230 Route 12,"
8,A17,Olive,Pless,,opless@pctech.com,234-765-2233,15 Horse Alley,,Oakland,PA,15213-8260,10/12/2000,9/16/2002,West,7500,213,Olive,"15 Horse Alley,"
9,A19,Remmy,Walker,L,walk.r@aol.com,969-234-8367,100 Silver Hwy,,Oakland,PA,15213,6/1/2012,8/1/2012,South,20000,0,Remmy L,"100 Silver Hwy,"

Usuwam niepotrzebne kolumny i zmieniam ich nazwy.

In [18]:
df1 = df1[['ID', 'name', 'last name', 'Address', 'city', 'state', 'zip', 'email', 'phone']]

In [19]:
df2 = df2[['cusnum', 'name', 'cuslname', 'address', 'cuscity', 'cusstate', 'cuszip', 'cusemail', 'cusphone']]

In [20]:
df1

,ID,name,last name,Address,city,state,zip,email,phone
0,C1,Jill,Franks,111 Lake Dr,Pgh,Pa,15212.0,jf773@hotmail.com,NaN
1,C2,Sal,Yates,57 College Way,Morgantown,WV,26501.0,NaN,724-234-6542
2,C3,Will,Ratliff,544 Fifth Ave,Pgh,Pa,15219.0,ratty@mail.com,NaN
3,C4,Fran,Vicks,10332 West Street,McCandless,PA,15234.0,NaN,904-123-8337
4,C5,Kline's,None,500 West South Street,Pgh,PA,15219.0,klines2@klines.com,NaN
5,C6,Olive,Pless,"6767 W 54th Street, Apt B",NaN,NaN,NaN,opless@newpc.com,NaN

In [21]:
df2

,cusnum,name,cuslname,address,cuscity,cusstate,cuszip,cusemail,cusphone
0,A01,Jim A,Semp,"123 Main Street, Suite 23",Pittsburgh,PA,15217-2233,jsemp@mail.com,123-654-2344
1,A03,Laura,Vail,"23 Oak Lane,",Morgantown,WV,26501,laura.vail@hotmail.com,756-345-6789
2,A05,Al's Bakery,NaN,"846 Fifth Ave,",Pittsburgh,PA,15219-1222,al@alsbakery.com,213-543-2342
3,A07,Janet R,Wendell,"23212 Fern Circle, Apt 100",Washington,DC,20001,jwen@yahoo.com,434-786-3453
4,A09,Alicia,Albert,"432 Forbes Ave,",Pittsburgh,PA,15229,aalbert@gmail.com,234-678-9234
5,A11,Henry,Kobb,"10 Dairy Way, 2nd Floor",Pittsburgh,PA,15229-8821,hank@kobbfam.net,234-098-7464
6,A13,Corner Market,NaN,"1500 Bruster Way,",Ross,PA,15237,manager@cornermarket.com,222-837-6455
7,A15,Paul E,Tolby,"230 Route 12,",Ross,PA,15237,pt23@school.edu,995-234-5656
8,A17,Olive,Pless,"15 Horse Alley,",Oakland,PA,15213-8260,opless@pctech.com,234-765-2233
9,A19,Remmy L,Walker,"100 Silver Hwy,",Oakland,PA,15213,walk.r@aol.com,969-234-8367

In [22]:
df1.columns = ['ID', 'name', 'last name', 'address', 'city', 'state', 'zip', 'e-mail', 'phone']
df2.columns = ['ID', 'name', 'last name', 'address', 'city', 'state', 'zip', 'e-mail', 'phone']

In [23]:
df1

,ID,name,last name,address,city,state,zip,e-mail,phone
0,C1,Jill,Franks,111 Lake Dr,Pgh,Pa,15212.0,jf773@hotmail.com,NaN
1,C2,Sal,Yates,57 College Way,Morgantown,WV,26501.0,NaN,724-234-6542
2,C3,Will,Ratliff,544 Fifth Ave,Pgh,Pa,15219.0,ratty@mail.com,NaN
3,C4,Fran,Vicks,10332 West Street,McCandless,PA,15234.0,NaN,904-123-8337
4,C5,Kline's,None,500 West South Street,Pgh,PA,15219.0,klines2@klines.com,NaN
5,C6,Olive,Pless,"6767 W 54th Street, Apt B",NaN,NaN,NaN,opless@newpc.com,NaN

In [24]:
df2

,ID,name,last name,address,city,state,zip,e-mail,phone
0,A01,Jim A,Semp,"123 Main Street, Suite 23",Pittsburgh,PA,15217-2233,jsemp@mail.com,123-654-2344
1,A03,Laura,Vail,"23 Oak Lane,",Morgantown,WV,26501,laura.vail@hotmail.com,756-345-6789
2,A05,Al's Bakery,NaN,"846 Fifth Ave,",Pittsburgh,PA,15219-1222,al@alsbakery.com,213-543-2342
3,A07,Janet R,Wendell,"23212 Fern Circle, Apt 100",Washington,DC,20001,jwen@yahoo.com,434-786-3453
4,A09,Alicia,Albert,"432 Forbes Ave,",Pittsburgh,PA,15229,aalbert@gmail.com,234-678-9234
5,A11,Henry,Kobb,"10 Dairy Way, 2nd Floor",Pittsburgh,PA,15229-8821,hank@kobbfam.net,234-098-7464
6,A13,Corner Market,NaN,"1500 Bruster Way,",Ross,PA,15237,manager@cornermarket.com,222-837-6455
7,A15,Paul E,Tolby,"230 Route 12,",Ross,PA,15237,pt23@school.edu,995-234-5656
8,A17,Olive,Pless,"15 Horse Alley,",Oakland,PA,15213-8260,opless@pctech.com,234-765-2233
9,A19,Remmy L,Walker,"100 Silver Hwy,",Oakland,PA,15213,walk.r@aol.com,969-234-8367

Poprawiam nazwy miast, wielkość liter w stanach, kody pocztowe.

In [25]:
df1 = df1.replace({'Pgh': 'Pittsburgh'})
df1['state'] = df1['state'].str.upper()
df1['zip'] = df1['zip'].astype(str) 
df1['zip'] = df1['zip'].str[:5]

In [26]:
df1

,ID,name,last name,address,city,state,zip,e-mail,phone
0,C1,Jill,Franks,111 Lake Dr,Pittsburgh,PA,15212,jf773@hotmail.com,NaN
1,C2,Sal,Yates,57 College Way,Morgantown,WV,26501,NaN,724-234-6542
2,C3,Will,Ratliff,544 Fifth Ave,Pittsburgh,PA,15219,ratty@mail.com,NaN
3,C4,Fran,Vicks,10332 West Street,McCandless,PA,15234,NaN,904-123-8337
4,C5,Kline's,None,500 West South Street,Pittsburgh,PA,15219,klines2@klines.com,NaN
5,C6,Olive,Pless,"6767 W 54th Street, Apt B",NaN,NaN,nan,opless@newpc.com,NaN

In [27]:
df2.loc[:, 'zip'] = df2['zip'].str[:5]

In [28]:
df2

,ID,name,last name,address,city,state,zip,e-mail,phone
0,A01,Jim A,Semp,"123 Main Street, Suite 23",Pittsburgh,PA,15217,jsemp@mail.com,123-654-2344
1,A03,Laura,Vail,"23 Oak Lane,",Morgantown,WV,26501,laura.vail@hotmail.com,756-345-6789
2,A05,Al's Bakery,NaN,"846 Fifth Ave,",Pittsburgh,PA,15219,al@alsbakery.com,213-543-2342
3,A07,Janet R,Wendell,"23212 Fern Circle, Apt 100",Washington,DC,20001,jwen@yahoo.com,434-786-3453
4,A09,Alicia,Albert,"432 Forbes Ave,",Pittsburgh,PA,15229,aalbert@gmail.com,234-678-9234
5,A11,Henry,Kobb,"10 Dairy Way, 2nd Floor",Pittsburgh,PA,15229,hank@kobbfam.net,234-098-7464
6,A13,Corner Market,NaN,"1500 Bruster Way,",Ross,PA,15237,manager@cornermarket.com,222-837-6455
7,A15,Paul E,Tolby,"230 Route 12,",Ross,PA,15237,pt23@school.edu,995-234-5656
8,A17,Olive,Pless,"15 Horse Alley,",Oakland,PA,15213,opless@pctech.com,234-765-2233
9,A19,Remmy L,Walker,"100 Silver Hwy,",Oakland,PA,15213,walk.r@aol.com,969-234-8367

Łączę tabele.

In [29]:
Customer = pd.concat([df2, df1], ignore_index = True)

In [30]:
Customer

,ID,name,last name,address,city,state,zip,e-mail,phone
0,A01,Jim A,Semp,"123 Main Street, Suite 23",Pittsburgh,PA,15217,jsemp@mail.com,123-654-2344
1,A03,Laura,Vail,"23 Oak Lane,",Morgantown,WV,26501,laura.vail@hotmail.com,756-345-6789
2,A05,Al's Bakery,NaN,"846 Fifth Ave,",Pittsburgh,PA,15219,al@alsbakery.com,213-543-2342
3,A07,Janet R,Wendell,"23212 Fern Circle, Apt 100",Washington,DC,20001,jwen@yahoo.com,434-786-3453
4,A09,Alicia,Albert,"432 Forbes Ave,",Pittsburgh,PA,15229,aalbert@gmail.com,234-678-9234
5,A11,Henry,Kobb,"10 Dairy Way, 2nd Floor",Pittsburgh,PA,15229,hank@kobbfam.net,234-098-7464
6,A13,Corner Market,NaN,"1500 Bruster Way,",Ross,PA,15237,manager@cornermarket.com,222-837-6455
7,A15,Paul E,Tolby,"230 Route 12,",Ross,PA,15237,pt23@school.edu,995-234-5656
8,A17,Olive,Pless,"15 Horse Alley,",Oakland,PA,15213,opless@pctech.com,234-765-2233
9,A19,Remmy L,Walker,"100 Silver Hwy,",Oakland,PA,15213,walk.r@aol.com,969-234-8367
10,C1,Jill,Franks,111 Lake Dr,Pittsburgh,PA,15212,jf773@hotmail.com,NaN
11,C2,Sal,Yates,57 College Way,Morgantown,WV,26501,NaN,724-234-6542
12,C3,Will,Ratliff,544 Fifth Ave,Pittsburgh,PA,15219,ratty@mail.com,NaN
13,C4,Fran,Vicks,10332 West Street,McCandless,PA,15234,NaN,904-123-8337
14,C5,Kline's,None,500 West South Street,Pittsburgh,PA,15219,klines2@klines.com,NaN
15,C6,Olive,Pless,"6767 W 54th Street, Apt B",NaN,NaN,nan,opless@newpc.com,NaN

Usuwam NaN.

In [31]:
Customer = Customer.replace({None: '-'})

In [32]:
Customer

,ID,name,last name,address,city,state,zip,e-mail,phone
0,A01,Jim A,Semp,"123 Main Street, Suite 23",Pittsburgh,PA,15217,jsemp@mail.com,123-654-2344
1,A03,Laura,Vail,"23 Oak Lane,",Morgantown,WV,26501,laura.vail@hotmail.com,756-345-6789
2,A05,Al's Bakery,-,"846 Fifth Ave,",Pittsburgh,PA,15219,al@alsbakery.com,213-543-2342
3,A07,Janet R,Wendell,"23212 Fern Circle, Apt 100",Washington,DC,20001,jwen@yahoo.com,434-786-3453
4,A09,Alicia,Albert,"432 Forbes Ave,",Pittsburgh,PA,15229,aalbert@gmail.com,234-678-9234
5,A11,Henry,Kobb,"10 Dairy Way, 2nd Floor",Pittsburgh,PA,15229,hank@kobbfam.net,234-098-7464
6,A13,Corner Market,-,"1500 Bruster Way,",Ross,PA,15237,manager@cornermarket.com,222-837-6455
7,A15,Paul E,Tolby,"230 Route 12,",Ross,PA,15237,pt23@school.edu,995-234-5656
8,A17,Olive,Pless,"15 Horse Alley,",Oakland,PA,15213,opless@pctech.com,234-765-2233
9,A19,Remmy L,Walker,"100 Silver Hwy,",Oakland,PA,15213,walk.r@aol.com,969-234-8367
10,C1,Jill,Franks,111 Lake Dr,Pittsburgh,PA,15212,jf773@hotmail.com,-
11,C2,Sal,Yates,57 College Way,Morgantown,WV,26501,-,724-234-6542
12,C3,Will,Ratliff,544 Fifth Ave,Pittsburgh,PA,15219,ratty@mail.com,-
13,C4,Fran,Vicks,10332 West Street,McCandless,PA,15234,-,904-123-8337
14,C5,Kline's,-,500 West South Street,Pittsburgh,PA,15219,klines2@klines.com,-
15,C6,Olive,Pless,"6767 W 54th Street, Apt B",-,-,nan,opless@newpc.com,-

Usuwam powtórki.

In [33]:
list = Customer['name'].values.tolist()
list

['Jim A',
 'Laura ',
 "Al's Bakery ",
 'Janet R',
 'Alicia ',
 'Henry ',
 'Corner Market ',
 'Paul E',
 'Olive ',
 'Remmy L',
 'Jill',
 'Sal',
 'Will',
 'Fran',
 "Kline's",
 'Olive']

In [34]:
Customer['name'] = Customer['name'].str.strip()

In [35]:
Customer = Customer.drop_duplicates(subset = ['name', 'last name'])

In [36]:
Customer

,ID,name,last name,address,city,state,zip,e-mail,phone
0,A01,Jim A,Semp,"123 Main Street, Suite 23",Pittsburgh,PA,15217,jsemp@mail.com,123-654-2344
1,A03,Laura,Vail,"23 Oak Lane,",Morgantown,WV,26501,laura.vail@hotmail.com,756-345-6789
2,A05,Al's Bakery,-,"846 Fifth Ave,",Pittsburgh,PA,15219,al@alsbakery.com,213-543-2342
3,A07,Janet R,Wendell,"23212 Fern Circle, Apt 100",Washington,DC,20001,jwen@yahoo.com,434-786-3453
4,A09,Alicia,Albert,"432 Forbes Ave,",Pittsburgh,PA,15229,aalbert@gmail.com,234-678-9234
5,A11,Henry,Kobb,"10 Dairy Way, 2nd Floor",Pittsburgh,PA,15229,hank@kobbfam.net,234-098-7464
6,A13,Corner Market,-,"1500 Bruster Way,",Ross,PA,15237,manager@cornermarket.com,222-837-6455
7,A15,Paul E,Tolby,"230 Route 12,",Ross,PA,15237,pt23@school.edu,995-234-5656
8,A17,Olive,Pless,"15 Horse Alley,",Oakland,PA,15213,opless@pctech.com,234-765-2233
9,A19,Remmy L,Walker,"100 Silver Hwy,",Oakland,PA,15213,walk.r@aol.com,969-234-8367
10,C1,Jill,Franks,111 Lake Dr,Pittsburgh,PA,15212,jf773@hotmail.com,-
11,C2,Sal,Yates,57 College Way,Morgantown,WV,26501,-,724-234-6542
12,C3,Will,Ratliff,544 Fifth Ave,Pittsburgh,PA,15219,ratty@mail.com,-
13,C4,Fran,Vicks,10332 West Street,McCandless,PA,15234,-,904-123-8337
14,C5,Kline's,-,500 West South Street,Pittsburgh,PA,15219,klines2@klines.com,-

Ujednolicam indeksy.

In [37]:
import numpy as np

In [38]:
Customer.drop('ID', axis = 1, inplace = True)

In [39]:
Customer

,name,last name,address,city,state,zip,e-mail,phone
0,Jim A,Semp,"123 Main Street, Suite 23",Pittsburgh,PA,15217,jsemp@mail.com,123-654-2344
1,Laura,Vail,"23 Oak Lane,",Morgantown,WV,26501,laura.vail@hotmail.com,756-345-6789
2,Al's Bakery,-,"846 Fifth Ave,",Pittsburgh,PA,15219,al@alsbakery.com,213-543-2342
3,Janet R,Wendell,"23212 Fern Circle, Apt 100",Washington,DC,20001,jwen@yahoo.com,434-786-3453
4,Alicia,Albert,"432 Forbes Ave,",Pittsburgh,PA,15229,aalbert@gmail.com,234-678-9234
5,Henry,Kobb,"10 Dairy Way, 2nd Floor",Pittsburgh,PA,15229,hank@kobbfam.net,234-098-7464
6,Corner Market,-,"1500 Bruster Way,",Ross,PA,15237,manager@cornermarket.com,222-837-6455
7,Paul E,Tolby,"230 Route 12,",Ross,PA,15237,pt23@school.edu,995-234-5656
8,Olive,Pless,"15 Horse Alley,",Oakland,PA,15213,opless@pctech.com,234-765-2233
9,Remmy L,Walker,"100 Silver Hwy,",Oakland,PA,15213,walk.r@aol.com,969-234-8367
10,Jill,Franks,111 Lake Dr,Pittsburgh,PA,15212,jf773@hotmail.com,-
11,Sal,Yates,57 College Way,Morgantown,WV,26501,-,724-234-6542
12,Will,Ratliff,544 Fifth Ave,Pittsburgh,PA,15219,ratty@mail.com,-
13,Fran,Vicks,10332 West Street,McCandless,PA,15234,-,904-123-8337
14,Kline's,-,500 West South Street,Pittsburgh,PA,15219,klines2@klines.com,-

In [40]:
Customer.insert(0, "ID", np.arange(1, 16, 1), True)

In [41]:
Customer

,ID,name,last name,address,city,state,zip,e-mail,phone
0,1,Jim A,Semp,"123 Main Street, Suite 23",Pittsburgh,PA,15217,jsemp@mail.com,123-654-2344
1,2,Laura,Vail,"23 Oak Lane,",Morgantown,WV,26501,laura.vail@hotmail.com,756-345-6789
2,3,Al's Bakery,-,"846 Fifth Ave,",Pittsburgh,PA,15219,al@alsbakery.com,213-543-2342
3,4,Janet R,Wendell,"23212 Fern Circle, Apt 100",Washington,DC,20001,jwen@yahoo.com,434-786-3453
4,5,Alicia,Albert,"432 Forbes Ave,",Pittsburgh,PA,15229,aalbert@gmail.com,234-678-9234
5,6,Henry,Kobb,"10 Dairy Way, 2nd Floor",Pittsburgh,PA,15229,hank@kobbfam.net,234-098-7464
6,7,Corner Market,-,"1500 Bruster Way,",Ross,PA,15237,manager@cornermarket.com,222-837-6455
7,8,Paul E,Tolby,"230 Route 12,",Ross,PA,15237,pt23@school.edu,995-234-5656
8,9,Olive,Pless,"15 Horse Alley,",Oakland,PA,15213,opless@pctech.com,234-765-2233
9,10,Remmy L,Walker,"100 Silver Hwy,",Oakland,PA,15213,walk.r@aol.com,969-234-8367
10,11,Jill,Franks,111 Lake Dr,Pittsburgh,PA,15212,jf773@hotmail.com,-
11,12,Sal,Yates,57 College Way,Morgantown,WV,26501,-,724-234-6542
12,13,Will,Ratliff,544 Fifth Ave,Pittsburgh,PA,15219,ratty@mail.com,-
13,14,Fran,Vicks,10332 West Street,McCandless,PA,15234,-,904-123-8337
14,15,Kline's,-,500 West South Street,Pittsburgh,PA,15219,klines2@klines.com,-

In [42]:
Customer.set_index('ID')

,name,last name,address,city,state,zip,e-mail,phone
ID,,,,,,,,
1,Jim A,Semp,"123 Main Street, Suite 23",Pittsburgh,PA,15217,jsemp@mail.com,123-654-2344
2,Laura,Vail,"23 Oak Lane,",Morgantown,WV,26501,laura.vail@hotmail.com,756-345-6789
3,Al's Bakery,-,"846 Fifth Ave,",Pittsburgh,PA,15219,al@alsbakery.com,213-543-2342
4,Janet R,Wendell,"23212 Fern Circle, Apt 100",Washington,DC,20001,jwen@yahoo.com,434-786-3453
5,Alicia,Albert,"432 Forbes Ave,",Pittsburgh,PA,15229,aalbert@gmail.com,234-678-9234
6,Henry,Kobb,"10 Dairy Way, 2nd Floor",Pittsburgh,PA,15229,hank@kobbfam.net,234-098-7464
7,Corner Market,-,"1500 Bruster Way,",Ross,PA,15237,manager@cornermarket.com,222-837-6455
8,Paul E,Tolby,"230 Route 12,",Ross,PA,15237,pt23@school.edu,995-234-5656
9,Olive,Pless,"15 Horse Alley,",Oakland,PA,15213,opless@pctech.com,234-765-2233
10,Remmy L,Walker,"100 Silver Hwy,",Oakland,PA,15213,walk.r@aol.com,969-234-8367
11,Jill,Franks,111 Lake Dr,Pittsburgh,PA,15212,jf773@hotmail.com,-
12,Sal,Yates,57 College Way,Morgantown,WV,26501,-,724-234-6542
13,Will,Ratliff,544 Fifth Ave,Pittsburgh,PA,15219,ratty@mail.com,-
14,Fran,Vicks,10332 West Street,McCandless,PA,15234,-,904-123-8337
15,Kline's,-,500 West South Street,Pittsburgh,PA,15219,klines2@klines.com,-