In [1]:
import pandas as pd
import numpy as np

In [2]:
storey_species = pd.read_csv("f_storey_species.txt", sep = "\t")

In [3]:
species = pd.read_csv("f_tree_species_dic.txt", sep = "\t")

In [4]:
storey_species = pd.merge(storey_species, species[['species_cd','species_name']], on = 'species_cd', how = 'left')

In [5]:
storey_species

,arodes_int_num,a_year,storey_cd,sp_rank_order_act,species_cd,species_age,part_cd_act,site_class_cd,height,bhd,volume,species_name
0,121000005,2021,PODSZ,5,BRZ,NaN,NaN,NaN,NaN,NaN,NaN,brzoza brodawkowata
1,121000005,2021,PODSZ,4,ŚW,NaN,NaN,NaN,NaN,NaN,NaN,świerk pospolity
2,121000005,2021,PODSZ,3,DB,NaN,NaN,NaN,NaN,NaN,NaN,dąb nieokreślony
3,121000005,2021,PODSZ,2,JAŁ,NaN,NaN,NaN,NaN,NaN,NaN,jałowiec pospolity
4,121000005,2021,PODSZ,1,CZM,NaN,NaN,NaN,NaN,NaN,NaN,czeremcha pospolita
...,...,...,...,...,...,...,...,...,...,...,...,...
66938,121019891,2021,ZADRZEW,5,SO,92.0,NaN,NaN,29.0,40.0,10.0,sosna zwyczajna
66939,121019891,2021,ZADRZEW,4,OL,46.0,NaN,NaN,15.0,17.0,10.0,olsza czarna
66940,121019891,2021,ZADRZEW,3,BRZ,46.0,NaN,NaN,16.0,18.0,10.0,brzoza brodawkowata
66941,121019891,2021,ZADRZEW,2,BRZ,66.0,NaN,NaN,21.0,23.0,10.0,brzoza brodawkowata
66942,121019891,2021,ZADRZEW,1,OL,66.0,NaN,NaN,20.0,21.0,80.0,olsza czarna

In [6]:
df = storey_species[~storey_species['volume'].isna()]

In [7]:
df

,arodes_int_num,a_year,storey_cd,sp_rank_order_act,species_cd,species_age,part_cd_act,site_class_cd,height,bhd,volume,species_name
13,121000005,2021,DRZEW,1,SO,67.0,10,IA,26.0,29.0,332.078788,sosna zwyczajna
24,121000013,2021,DRZEW,1,SO,71.0,10,I,24.0,26.0,320.141731,sosna zwyczajna
25,121000009,2021,DRZEW,4,BRZ,86.0,1,I,28.0,31.0,30.678745,brzoza brodawkowata
36,121000016,2021,DRZEW,2,ŚW,96.0,1,II,28.0,37.0,54.475528,świerk pospolity
37,121000016,2021,DRZEW,1,SO,186.0,9,II,27.0,50.0,291.453288,sosna zwyczajna
...,...,...,...,...,...,...,...,...,...,...,...,...
66938,121019891,2021,ZADRZEW,5,SO,92.0,NaN,NaN,29.0,40.0,10.000000,sosna zwyczajna
66939,121019891,2021,ZADRZEW,4,OL,46.0,NaN,NaN,15.0,17.0,10.000000,olsza czarna
66940,121019891,2021,ZADRZEW,3,BRZ,46.0,NaN,NaN,16.0,18.0,10.000000,brzoza brodawkowata
66941,121019891,2021,ZADRZEW,2,BRZ,66.0,NaN,NaN,21.0,23.0,10.000000,brzoza brodawkowata
66942,121019891,2021,ZADRZEW,1,OL,66.0,NaN,NaN,20.0,21.0,80.000000,olsza czarna

In [8]:
species_groups = df.groupby('species_cd')

In [9]:
species_groups[['species_name']].first()

                              species_name
species_cd
BK          buk pospolity
BRZ         brzoza brodawkowata
CZR         czereśnia pospolita
DB          dąb nieokreślony
GB          grab pospolity
GR          grusza pospolita
IWA         wierzba iwa
JB          jabłoń dzika
JS          jesion wyniosły
KL          klon pospolity
KSZ         kasztanowiec biały
LP          lipa drobnolistna
MD          modrzew europejski
OL          olsza czarna
OS          topola osika
SO          sosna zwyczajna
TP          topola biała
WB          wierzba biała
WIŚ         wiśnia pospolita
WZ          wiąz pospolity
ŚW          świerk pospolity

In [10]:
df = df.pivot_table(index = 'arodes_int_num', columns = 'species_name', values = 'volume', aggfunc = 'sum')

In [11]:
df

species_name,brzoza brodawkowata,buk pospolity,czereśnia pospolita,dąb nieokreślony,grab pospolity,grusza pospolita,jabłoń dzika,jesion wyniosły,kasztanowiec biały,klon pospolity,...,modrzew europejski,olsza czarna,sosna zwyczajna,topola biała,topola osika,wierzba biała,wierzba iwa,wiąz pospolity,wiśnia pospolita,świerk pospolity
arodes_int_num,,,,,,,,,,,,,,,,,,,,,
121000005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,332.078788,NaN,NaN,NaN,NaN,NaN,NaN,NaN
121000009,30.678745,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,318.432531,NaN,NaN,NaN,NaN,NaN,NaN,142.151855
121000013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,320.141731,NaN,NaN,NaN,NaN,NaN,NaN,NaN
121000016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,291.453288,NaN,NaN,NaN,NaN,NaN,NaN,54.475528
121000018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,338.007038,NaN,NaN,NaN,NaN,NaN,NaN,40.596979
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121023901,5.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
121023903,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,345.911403,NaN,NaN,NaN,NaN,NaN,NaN,NaN
121023904,16.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,40.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
121023907,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,29.830845,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.116324
121023917,40.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,90.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df.columns = df.columns.str.strip()

In [13]:
df.columns

Index(['brzoza brodawkowata', 'buk pospolity', 'czereśnia pospolita',
       'dąb nieokreślony', 'grab pospolity', 'grusza pospolita',
       'jabłoń dzika', 'jesion wyniosły', 'kasztanowiec biały',
       'klon pospolity', 'lipa drobnolistna', 'modrzew europejski',
       'olsza czarna', 'sosna zwyczajna', 'topola biała', 'topola osika',
       'wierzba biała', 'wierzba iwa', 'wiąz pospolity', 'wiśnia pospolita',
       'świerk pospolity'],
      dtype='object', name='species_name')

In [14]:
topola = df['topola biała'].fillna(0) + df['topola osika'].fillna(0)
wierzba = df['wierzba biała'].fillna(0) + df['wierzba iwa'].fillna(0)

In [15]:
df = df.drop(columns = ['topola biała', 'topola osika', 'wierzba biała', 'wierzba iwa'])

In [16]:
df['topola'] = topola
df['wierzba'] = wierzba

In [17]:
df

species_name,brzoza brodawkowata,buk pospolity,czereśnia pospolita,dąb nieokreślony,grab pospolity,grusza pospolita,jabłoń dzika,jesion wyniosły,kasztanowiec biały,klon pospolity,lipa drobnolistna,modrzew europejski,olsza czarna,sosna zwyczajna,wiąz pospolity,wiśnia pospolita,świerk pospolity,topola,wierzba
arodes_int_num,,,,,,,,,,,,,,,,,,,
121000005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,332.078788,NaN,NaN,NaN,0.0,0.0
121000009,30.678745,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,318.432531,NaN,NaN,142.151855,0.0,0.0
121000013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,320.141731,NaN,NaN,NaN,0.0,0.0
121000016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,291.453288,NaN,NaN,54.475528,0.0,0.0
121000018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,338.007038,NaN,NaN,40.596979,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121023901,5.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
121023903,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,345.911403,NaN,NaN,NaN,0.0,0.0
121023904,16.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.000000,NaN,NaN,NaN,0.0,0.0
121023907,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29.830845,NaN,NaN,NaN,40.116324,0.0,0.0
121023917,40.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90.000000,NaN,NaN,NaN,NaN,0.0,0.0

In [18]:
df = df.replace(0, np.nan)

In [19]:
df2 = df.notnull()

In [20]:
df2

species_name,brzoza brodawkowata,buk pospolity,czereśnia pospolita,dąb nieokreślony,grab pospolity,grusza pospolita,jabłoń dzika,jesion wyniosły,kasztanowiec biały,klon pospolity,lipa drobnolistna,modrzew europejski,olsza czarna,sosna zwyczajna,wiąz pospolity,wiśnia pospolita,świerk pospolity,topola,wierzba
arodes_int_num,,,,,,,,,,,,,,,,,,,
121000005,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
121000009,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False
121000013,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
121000016,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False
121000018,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121023901,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
121023903,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
121023904,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
121023907,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False
121023917,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False

In [21]:
subarea = pd.read_csv("f_subarea.txt", sep = "\t")

In [22]:
subarea

,arodes_int_num,a_year,area_type_cd,site_type_cd,moisture_cd,degradation_cd,soil_subtype_cd,plant_comm_cd,stand_struct_cd,forest_func_cd,silviculture_cd,rotation_age,sub_area,veg_cover_cd,damage_degree,cause_cd
0,121000013,2021,D-STAN,BŚW,Ś,N2,RDb,NaN,DRZEW,OCHR,O,120.0,7.89,MSZC,NaN,NaN
1,121000016,2021,D-STAN,BMŚW,Ś,N2,RDw,NaN,DRZEW,OCHR,S,120.0,1.45,MSZC,NaN,NaN
2,121000100,2021,D-STAN,BŚW,Ś,N2,RDb,NaN,DRZEW,OCHR,O,120.0,5.53,MSZC,NaN,NaN
3,121000104,2021,D-STAN,BMŚW,Ś,N2,RDb,NaN,DRZEW,OCHR,O,120.0,3.20,MSZC,NaN,NaN
4,121000106,2021,D-STAN,BŚW,Ś,N2,RDb,NaN,DRZEW,OCHR,O,120.0,2.63,MSZC,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8408,121020583,2021,D-STAN,BMŚW,SŚ,N2,RDw,NaN,DRZEW,OCHR,O,120.0,2.88,ZAD,20.0,ZWIERZ
8409,121020585,2021,D-STAN,OL,BM,N2,Tn,NaN,DRZEW,OCHR,O,80.0,3.79,SZAD,NaN,NaN
8410,121020590,2021,D-STAN,OL,BM,N2,Tn,NaN,DRZEW,OCHR,O,80.0,3.01,ZAD,NaN,NaN
8411,121020597,2021,D-STAN,OLJ,ŁZ,N2,MRm,NaN,DRZEW,OCHR,O,80.0,1.81,SZCH,NaN,NaN
8412,121020599,2021,D-STAN,OLJ,ŁZ,N2,MRm,NaN,DRZEW,OCHR,O,80.0,2.32,SZCH,NaN,NaN

In [23]:
subarea.columns = subarea.columns.str.strip()

In [24]:
df2 = pd.merge(df2, subarea[['arodes_int_num', 'soil_subtype_cd', 'forest_func_cd', 'moisture_cd', 'site_type_cd']], on = 'arodes_int_num', how = 'left')

In [25]:
df2

,arodes_int_num,brzoza brodawkowata,buk pospolity,czereśnia pospolita,dąb nieokreślony,grab pospolity,grusza pospolita,jabłoń dzika,jesion wyniosły,kasztanowiec biały,...,sosna zwyczajna,wiąz pospolity,wiśnia pospolita,świerk pospolity,topola,wierzba,soil_subtype_cd,forest_func_cd,moisture_cd,site_type_cd
0,121000005,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,RDb,OCHR,Ś,BŚW
1,121000009,True,False,False,False,False,False,False,False,False,...,True,False,False,True,False,False,RDw,OCHR,Ś,BMŚW
2,121000013,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,RDb,OCHR,Ś,BŚW
3,121000016,False,False,False,False,False,False,False,False,False,...,True,False,False,True,False,False,RDw,OCHR,Ś,BMŚW
4,121000018,False,False,False,False,False,False,False,False,False,...,True,False,False,True,False,False,RDb,OCHR,Ś,BŚW
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6053,121023901,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,NaN,NaN,NaN,NaN
6054,121023903,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,RDw,OCHR,Ś,BMŚW
6055,121023904,True,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,NaN,GOSP,Ś,BŚW
6056,121023907,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,Bgw,OCHR,WW,LMW
6057,121023917,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,NaN,GOSP,BM,LMB

In [26]:
df2[['site_type_cd']] = df2[['site_type_cd']].replace(to_replace = r'\bB\w+', value = 'bór', regex = True)
df2[['site_type_cd']] = df2[['site_type_cd']].replace(to_replace = r'\bL\w+', value = 'las', regex = True)
df2[['site_type_cd']] = df2[['site_type_cd']].replace(to_replace = r'\bO\w+', value = 'ols', regex = True)

In [27]:
soil_groups = df2.groupby('soil_subtype_cd').size().to_frame(name = 'count').reset_index()

In [28]:
soil_groups

   soil_subtype_cd  count
0           B           1
1           BR         33
2           BRwy       16
3           Bgms       54
4           Bgts       37
5           Bgw       686
6           Bw        582
7           CZms       20
8           CZw         2
9           Dw          1
10          Gt         59
11          Gts        10
12          Gw        117
13          MRm       107
14          MRms       65
15          MRw       119
16          Mt        223
17          OGw         3
18          Pbr         5
19          RDb      1407
20          RDbr       97
21          RDw      1327
22          Tn        561
23          Tp         26
24          Tw         59

In [29]:
soils = pd.read_csv("f_soil_subtype_dic.txt", sep = "\t")
soils

,date_from,date_to,soil_subtype_cd,soil_subtype_name,soil_subtype_nr
0,01-01-1970,NaN,AK,Gleby kulturoziemne ...,103
1,01-01-1970,NaN,AKb,Kulturoziemy pobagienne ...,107
2,01-01-1970,NaN,AKhs,Hortisole ...,105
3,01-01-1970,NaN,AKl,Kulturoziemy leśne ...,106
4,01-01-1970,NaN,AKrs,Rigosole ...,104
...,...,...,...,...,...
118,01-01-1970,NaN,GBt,Gleby glejobielicowe torfiaste ...,119
119,01-01-1970,NaN,GBw,Gleby glejobielicowe właściwe ...,120
120,01-01-1970,NaN,Czd,Czarnoziemy zdegradowane ...,121
121,01-01-1970,NaN,MRmm,Gleby mineralno-murszowe ...,122
122,01-01-2011,NaN,CZwy,Czarne ziemie wyługowane ...,34

In [30]:
soil_groups = pd.merge(soil_groups, soils[['soil_subtype_cd', 'soil_subtype_name']], on = 'soil_subtype_cd', how = 'left')

In [31]:
soil_groups

   soil_subtype_cd  count                                  soil_subtype_name
0           B           1  Gleby bielicowe                               ...
1           BR         33  Gleby brunatne                                ...
2           BRwy       16  Gleby brunatne wyługowane                     ...
3           Bgms       54  Gleby glejo-bielicowe murszaste               ...
4           Bgts       37  Gleby glejo-bielicowe torfiaste               ...
5           Bgw       686  Gleby glejo-bielicowe właściwe                ...
6           Bw        582  Gleby bielicowe właściwe                      ...
7           CZms       20  Czarne ziemie murszaste                       ...
8           CZw         2  Czarne ziemie właściwe                        ...
9           Dw          1  Gleby deluwialne właściwe                     ...
10          Gt         59  Gleby gruntowoglejowe torfowe                 ...
11          Gts        10  Gleby gruntowoglejowe torfiaste               ...
12          Gw        117  Gleby gruntowoglejowe właściwe                ...
13          MRm       107  Gleby mineralno-murszowe                      ...
14          MRms       65  Gleby murszaste                               ...
15          MRw       119  Gleby murszowate właściwe                     ...
16          Mt        223  Gleby torfowo-murszowe                        ...
17          OGw         3  Gleby opadowoglejowe właściwe                 ...
18          Pbr         5  Gleby płowe brunatne                          ...
19          RDb      1407  Gleby rdzawe bielicowe                        ...
20          RDbr       97  Gleby rdzawe brunatne                         ...
21          RDw      1327  Gleby rdzawe właściwe                         ...
22          Tn        561  Gleby torfowe torfowisk niskich               ...
23          Tp         26  Gleby torfowe torfowisk przejściowych         ...
24          Tw         59  Gleby torfowe torfowisk wysokich              ...

In [32]:
df2['soil_subtype_cd'] = df2['soil_subtype_cd'].str.strip()
df2['forest_func_cd'] = df2['forest_func_cd'].str.strip()
df2['moisture_cd'] = df2['moisture_cd'].str.strip()
df2['site_type_cd'] = df2['site_type_cd'].str.strip()

In [33]:
df2[['soil_subtype_cd']] = df2[['soil_subtype_cd']].replace('B', 'bielicowe')
df2[['soil_subtype_cd']] = df2[['soil_subtype_cd']].replace('Bw', 'bielicowe')
df2[['soil_subtype_cd']] = df2[['soil_subtype_cd']].replace('BR', 'brunatne')
df2[['soil_subtype_cd']] = df2[['soil_subtype_cd']].replace(to_replace = r'\bBR\w+', value = 'brunatne', regex = True)
df2[['soil_subtype_cd']] = df2[['soil_subtype_cd']].replace(to_replace = r'\bBg\w+', value = 'glejo_bielicowe', regex = True)
df2[['soil_subtype_cd']] = df2[['soil_subtype_cd']].replace(to_replace = r'\bCZ\w+', value = 'czarne_ziemie', regex = True)
df2[['soil_subtype_cd']] = df2[['soil_subtype_cd']].replace(to_replace = r'\bD\w+', value = 'deluwialne', regex = True)
df2[['soil_subtype_cd']] = df2[['soil_subtype_cd']].replace(to_replace = r'\bG\w+', value = 'gruntowoglejowe', regex = True)
df2[['soil_subtype_cd']] = df2[['soil_subtype_cd']].replace('MRm', 'mineralno_murszowe')
df2[['soil_subtype_cd']] = df2[['soil_subtype_cd']].replace('MRms', 'murszaste')
df2[['soil_subtype_cd']] = df2[['soil_subtype_cd']].replace('MRw', 'murszowate')
df2[['soil_subtype_cd']] = df2[['soil_subtype_cd']].replace('Mt', 'torfowo_murszowe')
df2[['soil_subtype_cd']] = df2[['soil_subtype_cd']].replace(to_replace = r'\bOG\w+', value = 'opadowoglejowe', regex = True)
df2[['soil_subtype_cd']] = df2[['soil_subtype_cd']].replace(to_replace = r'\bP\w+', value = 'płowe', regex = True)
df2[['soil_subtype_cd']] = df2[['soil_subtype_cd']].replace(to_replace = r'\bRD\w+', value = 'rdzawe', regex = True)
df2[['soil_subtype_cd']] = df2[['soil_subtype_cd']].replace(to_replace = r'\bT\w+', value = 'torfowe', regex = True)

In [34]:
df2

,arodes_int_num,brzoza brodawkowata,buk pospolity,czereśnia pospolita,dąb nieokreślony,grab pospolity,grusza pospolita,jabłoń dzika,jesion wyniosły,kasztanowiec biały,...,sosna zwyczajna,wiąz pospolity,wiśnia pospolita,świerk pospolity,topola,wierzba,soil_subtype_cd,forest_func_cd,moisture_cd,site_type_cd
0,121000005,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,rdzawe,OCHR,Ś,bór
1,121000009,True,False,False,False,False,False,False,False,False,...,True,False,False,True,False,False,rdzawe,OCHR,Ś,bór
2,121000013,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,rdzawe,OCHR,Ś,bór
3,121000016,False,False,False,False,False,False,False,False,False,...,True,False,False,True,False,False,rdzawe,OCHR,Ś,bór
4,121000018,False,False,False,False,False,False,False,False,False,...,True,False,False,True,False,False,rdzawe,OCHR,Ś,bór
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6053,121023901,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,NaN,NaN,NaN,NaN
6054,121023903,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,rdzawe,OCHR,Ś,bór
6055,121023904,True,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,NaN,GOSP,Ś,bór
6056,121023907,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,glejo_bielicowe,OCHR,WW,las
6057,121023917,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,NaN,GOSP,BM,las

In [35]:
df2.rename(columns = {'soil_subtype_cd':'gleba', 'forest_func_cd':'funkcja_lasu', 
                      'moisture_cd':'uwilgotnienie', 'site_type_cd':'siedlisko' }, inplace = True)

In [36]:
df2

,arodes_int_num,brzoza brodawkowata,buk pospolity,czereśnia pospolita,dąb nieokreślony,grab pospolity,grusza pospolita,jabłoń dzika,jesion wyniosły,kasztanowiec biały,...,sosna zwyczajna,wiąz pospolity,wiśnia pospolita,świerk pospolity,topola,wierzba,gleba,funkcja_lasu,uwilgotnienie,siedlisko
0,121000005,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,rdzawe,OCHR,Ś,bór
1,121000009,True,False,False,False,False,False,False,False,False,...,True,False,False,True,False,False,rdzawe,OCHR,Ś,bór
2,121000013,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,rdzawe,OCHR,Ś,bór
3,121000016,False,False,False,False,False,False,False,False,False,...,True,False,False,True,False,False,rdzawe,OCHR,Ś,bór
4,121000018,False,False,False,False,False,False,False,False,False,...,True,False,False,True,False,False,rdzawe,OCHR,Ś,bór
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6053,121023901,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,NaN,NaN,NaN,NaN
6054,121023903,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,rdzawe,OCHR,Ś,bór
6055,121023904,True,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,NaN,GOSP,Ś,bór
6056,121023907,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,glejo_bielicowe,OCHR,WW,las
6057,121023917,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,NaN,GOSP,BM,las

In [37]:
df2.any()

arodes_int_num         True
brzoza brodawkowata    True
buk pospolity          True
czereśnia pospolita    True
dąb nieokreślony       True
grab pospolity         True
grusza pospolita       True
jabłoń dzika           True
jesion wyniosły        True
kasztanowiec biały     True
klon pospolity         True
lipa drobnolistna      True
modrzew europejski     True
olsza czarna           True
sosna zwyczajna        True
wiąz pospolity         True
wiśnia pospolita       True
świerk pospolity       True
topola                 True
wierzba                True
gleba                  True
funkcja_lasu           True
uwilgotnienie          True
siedlisko              True
dtype: bool

In [38]:
df2.to_csv('out.txt')